/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedCount: typeof import('./components/AnimatedCount.vue')['default']
    BaseInput: typeof import('./components/input/BaseInput.vue')['default']
    ButtonGroup: typeof import('./components/button/ButtonGroup.vue')['default']
    ChipAvatar: typeof import('./components/chip/ChipAvatar.vue')['default']
    ChipWrapper: typeof import('./components/chip/ChipWrapper.vue')['default']
    CustomButton: typeof import('./components/button/CustomButton.vue')['default']
    CustomDatePicker: typeof import('./components/input/CustomDatePicker.vue')['default']
    CustomDropdown: typeof import('./components/input/CustomDropdown.vue')['default']
    CustomPaper: typeof import('./components/paper/CustomPaper.vue')['default']
    CustomTextInput: typeof import('./components/input/CustomTextInput.vue')['default']
    CustomToggle: typeof import('./components/input/CustomToggle.vue')['default']
    ListItem: typeof import('./components/list/ListItem.vue')['default']
    ListWrapper: typeof import('./components/list/ListWrapper.vue')['default']
    LoadingSpinner: typeof import('./components/loading/LoadingSpinner.vue')['default']
    LoadingSpinnerIcon: typeof import('./components/loading/LoadingSpinnerIcon.vue')['default']
    Modal: typeof import('./components/modal/Modal.vue')['default']
    Navigation: typeof import('./components/navigation/Navigation.vue')['default']
    NavigationAutoClose: typeof import('./components/navigation/NavigationAutoClose.vue')['default']
    NavigationItem: typeof import('./components/navigation/NavigationItem.vue')['default']
    PageHeader: typeof import('./components/header/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
